# Generated by Django 3.1 on 2020-08-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeJStest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Арендадержатель', 'verbose_name_plural': 'Арендадержатели'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
    ]
