# Generated by Django 3.1 on 2020-08-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeJStest', '0002_auto_20200831_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='build_id',
            new_name='id',
        ),
    ]
